### ISSUE TITLE
Alt Gr button not working

### ISSUE THREAD

**Issue by pavel-kalmykov-razgovorov** [stevenilsen123/mac-keyboard-behavior-in-windows#12]
I followed the tutorial, and the shortcuts were working as expected, but then I realized that the Altr Gr key stopped working, keeping me unable to type characters such as `\, |, @, #, ~, €, ¬` (Alt Gr + º, 1, 2, 3, 4, 5, 6).

Can someone please take a look at it? Thank you beforehand.

**Comment by stevenilsen123** [comment]
Sorry, I'm not familiar with `AltGr` since we don't use that key in the US. However, give this a try and let me know if it works:

In PowerToys, try remapping only the left modifier keys as such. I believe this should leave the AltGr key unmodified.
![image](https://user-images.githubusercontent.com/26051016/228564626-1efa2a0e-164f-4d94-94f4-14699e514d96.png)

If you can confirm that it works, I'll update the instuctions.

**Comment by stevenilsen123** [comment]
@pavel-razgovorov - are you able to confirm if the above fix worked?
